sudo: required
language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
before_install:
  - ./install-protobuf.sh
install: mvn install -DskipTests=true -Dgpg.skip=true -Dmaven.javadoc.skip=true -B -V
before_script:
  - echo $HOME
  - echo $JAVA_HOME

# travis detects and builds maven projects automatically
## script: mvn verify -Dgpg.skip=true
